name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
